version: '3.8'
services:
  ollama-container:
    image: kidong98/ollama-eeve
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "test -f /root/.ollama/models/manifests/registry.ollama.ai/library/EEVE-Korean-10.8B/latest || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 25

  streamlit-app:
    image: kidong98/samsung-rag
    ports:
      - 8501:8501
    depends_on:
      ollama-container:
        condition: service_healthy
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
